---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-user
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: guest
spec:
  memberOf: [guests]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-group
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: guests
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: davidmberg
spec:
  memberOf: [guests]  # Adjust this if the user belongs to a different group
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: testuser
spec:
  memberOf: [guests]  # Adjust this if the user belongs to a different group
